[package]
name = "rust-ncc"
version = "0.1.0"
authors = ["Brian Merchant <bhmerchant@gmail.com>, Ezgi Soylemezoglu <ezgisoylemezoglu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = "0.8.0"
rand_core = "0.6.0"
rand_distr = "0.4.0"
toml = "0.5.8"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
once_cell = "1.5.2"
tracing = "0.1.22"
avro-rs = "0.12.0"
avro-schema-derive = { path = "./avro-schema-derive" }
cairo-rs = "0.9.1"

[features]
debug_mode = []
animate = []
