[package]
name = "cbor_read_write"
version = "0.1.0"
authors = ["bhmerchant@gmail.com <bhmerchant@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
bincode = "1.3.1"
rust-ncc = { path = "../../"}
serde_cbor = "0.11.1"
