[package]
name = "playground"
version = "0.1.0"
authors = ["Brian Merchant <bhmerchant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
avro-rs = "0.10.0"
avro-schema-derive = { path = "../avro-schema-derive" }
serde = "1.0.114"
serde_json = "1.0.56"
